# Generated by Django 3.2.5 on 2021-07-16 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 16, 53, 49, 677743), verbose_name='Fecha de publicacion'),
        ),
    ]
